DROP TABLE IF EXISTS siscob.usuario;
CREATE TABLE siscob.usuario
  (
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME            VARCHAR(256) NOT NULL,
    ENDERECO        VARCHAR(256),
    CPF             VARCHAR(20),
    TELEFONE        VARCHAR(20),
    ATIVO           BOOLEAN NOT NULL,
    DATAPENALIZACAO DATE
  )
ENGINE=InnoDB
DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS siscob.publicacao;
CREATE TABLE siscob.publicacao
  (
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO          VARCHAR(256) NOT NULL,
    EDITORA         VARCHAR(256) NOT NULL,
    ANO             VARCHAR(11) NOT NULL,
    ATIVO           BOOLEAN NOT NULL,
    TIPO            VARCHAR(20) NOT NULL
  )
ENGINE=InnoDB
DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS siscob.periodico;
CREATE TABLE siscob.periodico
  (
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUMEDICAO       INT NOT NULL,
    MES             VARCHAR(256) NOT NULL
  )
ENGINE=InnoDB
DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS siscob.livro;
CREATE TABLE siscob.livro
  (
    ID                INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AUTORES           VARCHAR(256) NOT NULL,
    QTDEXEMPLARES     INT NOT NULL
  )
ENGINE=InnoDB
DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS siscob.itememprestimo;
CREATE TABLE siscob.itememprestimo
  (
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PUBLICACAO   INT NOT NULL,
    ID_EMPRESTIMO   INT NOT NULL,
    ATIVO           BOOLEAN NOT NULL,
    DATADEVOLUCAO   DATE
  )
ENGINE=InnoDB
DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS siscob.emprestimo;
CREATE TABLE siscob.emprestimo
  (
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATAEMPRESTIMO  DATE NOT NULL,
    DATADEVOLUCAO   DATE NOT NULL,
    ATIVO           BOOLEAN NOT NULL,
    ID_USUARIO      INT NOT NULL
  )
ENGINE=InnoDB
DEFAULT CHARSET=latin1;